### ISSUE TITLE
NG: notes for launching NG project - in Emulator

### ISSUE THREAD

**Issue by ionescu77** [heaven-dev/tv7SamsungNg#1]
Wow, so cool you managed to create and angular app for tizen.

I have ran gulp and I am trying to run locally.

Building in Tizen Studio takes a long time, maybe my laptop CPU is not good enough.

However with `ng serve` I get the same error I am used to (I am trying to use samsung tv api in angular 10).

It just can't find `webapis.js`, so I also get this `undefined` error :(

Any hints?

Thank you,

Raz

<img width="845" alt="Screenshot 2021-04-05 at 19 31 43" src="https://user-images.githubusercontent.com/8016748/113598481-dc6d6a00-9645-11eb-9e92-cb40dc5e73df.png">

<img width="733" alt="Screenshot 2021-04-05 at 18 20 47" src="https://user-images.githubusercontent.com/8016748/113598492-e0998780-9645-11eb-989d-4e9a3d85d87a.png">

**Comment by heaven-dev** [comment]
Hello @ionescu77 

Tizen studio is slow because it validates javascript and if javascript is minified it takes very long time. I recommend to use **vscode** and tizen **vscode tv extension** instead. Vscode tv extension page: https://developer.samsung.com/smarttv/develop/extension-libraries/vscode-extension.html

- If you are running app locally on a browser you have to set this https://github.com/heaven-dev/tv7SamsungNg/blob/main/src/app/helpers/constants.ts#L1 flag to **true**. In that case **webapis.js** is missing because it comes with **tizen**. It is available on emulator and TV. You can run app on browser without the **webapis.js** file if flag mentioned above is set to true.
- If you are trying to run app on emulator and you have windows OS then you can use this https://github.com/heaven-dev/tv7SamsungNg/blob/main/launch_win.bat bat file to **install** and **launch** the app on emulator. To run app on emulator version 6.0 type for example **launch_win.bat sv e6**. You can see other details on the file. At first use the **Certificate Manager** to create a certificate profile which name is **MyProfile**.
- I have seen that tizen emulators are unreliabe and they donät work similar like real device. It is better to test app on real device.

**Comment by ionescu77** [comment]
@heaven-dev Thanks for the quick reply.

I managed to get the TV frozen (SSSP TV, I installed with urlLauncher, previously worked, until I tried a tizen API version).
Found a key combination to erase an unresponsive app :) and I will cary on tomorrow.

I left the Tizen Studio to build overnight.

If you are available for some project hours please drop me a message (I have contact info on my github profile). 

Take care

**Comment by heaven-dev** [comment]
In any TV or emulator have to be a **Tizen 3.0** or newer to run this app.

**Comment by ionescu77** [comment]
Hi,

I gave a try with `launch.sh fi e6` (congrats the shell script is very nicelly writen).
I have the emulator for Tizen 6.0 started and


```bash
Build Web Application:  100% (10/10)

BUILD SUCCESSFUL

Output path : /Users/myuser/myProjects/tv7SamsungNg/tizen/dist/fi/dist/build
Excluded : [.project, .tproject, .build/*, .build, .sign/*, .sign, webUnitTest/*, webUnitTest, .externalToolBuilders/*, .externalToolBuilders, .buildResult/*, .buildResult, .settings/*, .settings, .package/*, .package, .tproject, .project, .sdk_delta.info, .rds_delta, *.wgt, .tizen-ui-builder-tool.xml]
Total time: 00:00:00.570
Warning: Not found tizen signature file
Warning: Not found tizen author signature file
Excludes File Pattern: {.manifest.tmp, .delta.lst}
Package File Location: /Users/myuser/myProjects/tv7SamsungNg/tizen/dist/fi/dist/app/TaivasTV7.wgt
Transferring the package...
Transferred the package: /Users/myuser/myProjects/tv7SamsungNg/tizen/dist/fi/dist/app/TaivasTV7.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install M8S1y7Jdfp.TaivasTV7
package_path /home/owner/share/tmp/sdk_tools/tmp/TaivasTV7.wgt
app_id[M8S1y7Jdfp.TaivasTV7] install start
app_id[M8S1y7Jdfp.TaivasTV7] installing[10]
app_id[M8S1y7Jdfp.TaivasTV7] installing[13]
app_id[M8S1y7Jdfp.TaivasTV7] installing[16]
app_id[M8S1y7Jdfp.TaivasTV7] installing[18]
app_id[M8S1y7Jdfp.TaivasTV7] installing[21]
app_id[M8S1y7Jdfp.TaivasTV7] installing[24]
app_id[M8S1y7Jdfp.TaivasTV7] install failed[118, -12], reason: Check certificate error :
spend time for wascmd is [648]ms
Failed to install Tizen application.
Total time: 00:00:01.509
Launching the Tizen application...
--------------------
Platform log view
--------------------
The app with ID: M8S1y7Jdfp.TaivasTV7 is not available for the user 5001
Could not launch the null application.
```

It seems there is certificate problem. I wonder why because my angular demo is able to pick-up the certificate automatically?

Because myself I have added the Tizen Studio tools to `PATH` before:

```bash
PATH=$PATH:/Users/myuser/tizen-studio/tools/ide/bin:/Users/myusers/tizen-studio/tools
```

And I am able to build my simple angular 10 app, but I never got so far as to be able to start it in the simulator. For my app I am only able to install the `wgt` produced during build on a TV in developer mode (via urlLauncher).

For example in `package.json` I added:

```json
    "tizen": "npm run build && npm run tizenPackage && cp sssp_config.xml dist/mm-tizen-angular/.buildResult/",
    "tizenPackage": "cd dist/mm-tizen-angular && tizen build-web && tizen package -t wgt -- .buildResult/",
    "tizenRun": "cd dist/mm-tizen-angular && sdb install .buildResult/mmTizenAngular.wgt && sdb shell  \"wrt-launcher '-s o59VSaNd4F.mmTizenAngular'\""
```

If I do `npm run tizen`:

```bash
Build Web Application:  100% (10/10)

BUILD SUCCESSFUL

Output path : /Users/myuser/myProjects/mm-tizen-angular/dist/mm-tizen-angular/.buildResult
Excluded : [.build/*, .build, .sign/*, .sign, webUnitTest/*, webUnitTest, .externalToolBuilders/*, .externalToolBuilders, .buildResult/*, .buildResult, .settings/*, .settings, .package/*, .package, .tproject, .project, .sdk_delta.info, .rds_delta, *.wgt, .tizen-ui-builder-tool.xml]
Total time: 00:00:00.638
The active profile is used for signing. If you want to sign with other profile, please use '--sign' option.
Author certficate: /Users/myuser/tizen-studio-data/keystore/author/RaziMacTizenTestKey.p12
Distributor1 certificate : /Users/myuser/tizen-studio/tools/certificate-generator/certificates/distributor/tizen-distributor-signer.p12
Excludes File Pattern: {.manifest.tmp, .delta.lst}
Ignore File: /Users/myuser/myProjects/mm-tizen-angular/dist/mm-tizen-angular/.buildResult/.manifest.tmp
Package File Location: /Users/myuser/myProjects/mm-tizen-angular/dist/mm-tizen-angular/.buildResult/mmTizenAngular.wgt
```

Thank you again

**Comment by ionescu77** [comment]
Man, your shell script is great:

- no ideea where I got the `sdb` above, but I just changed the `tizenRun` line in my `package.json` like this
```json
    "tizenRun": "cd dist/mm-tizen-angular && tizen install -- .buildResult -n mmTizenAngular.wgt -t T-samsung-6.0-x86 && tizen run -p o59VSaNd4F.mmTizenAngular -t T-samsung-6.0-x86"
```

Now I am able to start my app in the emulator!

I owe you some beers! 🍻

**Comment by heaven-dev** [comment]
Yes, I have been problems certificates and app signing in linux. In windows app signing works ok.

One output line of your script is: 
```
Author certficate: /Users/myuser/tizen-studio-data/keystore/author/TizenTestKey.p12
```

- How you created the Author certificate **TizenTestKey.p12** file?
- What is the content of the **~/tizen-studio-data/profile/profiles.xml** file?
  - you are not using **certificate profile** in packaging of app like me do: [-s MyProfile](https://github.com/heaven-dev/tv7SamsungNg/blob/main/launch.sh#L87)
- Can you share your shell script here?
- If you extract the signed app the content of it should be like:

![Screenshot_2021-04-07_08-56-34](https://user-images.githubusercontent.com/68559229/113817648-59e8c580-977f-11eb-8c55-7b67f2f26f08.png)

If the **author-signature.xml** and the **signature1.xml** files are there it means the app is signed.

**Comment by ionescu77** [comment]
Thank you for the info.
- the certificate was created in Tizen Studio, it is self signed, as I am not planning to publish
- I can see you left a commented-out section on your shell script related to copying `profile.xml` from `${PROFILE_DIR}`

INFO:
- I just removed `-s MyProfile` option from the `${TIZEN_EXE} package` and it picked my default signing profile
- I was able to launch using `launch.sh`, I can see the app in the simulator
- incredible work man!

PS:
- I was tired last night, of course I need to use my profile name from `profiles.xml` in the `launch.sh` script
```xml
<profile name="TizenTestProfile">
```
```bash
echo ${TIZEN_EXE} package -t wgt -s TizenTestProfile -- tizen/dist/${LANG}/dist/build -o tizen/dist/${LANG}/dist/app
```

**Comment by ionescu77** [comment]
Now I just need to understand the gulp pipeline.
As a backend developper (django), I have not used gulp for a long time (4 years)
If you are available for consulting services, let me know.

My app still does not run, yet.

- but must be the resources in my folder which are a mess
- for example I am missing `polyfills.js` and `runtime.js`

```bash
tree -L 2
.
├── author-signature.xml
├── config.xml
├── css
│   └── style.css
├── icon.png
├── images
│   └── tizen_32.png
├── index.html
├── js
│   └── main.js
├── mmTizenAngular.wgt
└── signature1.xml
```

- while yours looks much better
```bash
tree -L 3
.
├── app
│   └── TaivasTV7.wgt
└── build
    ├── assets
    | ...
    │   └── tv7logo.png
    ├── author-signature.xml
    ├── config.xml
    ├── css
    │   └── styles.css
    ├── index.html
    ├── js
    │   ├── main.js
    │   ├── polyfills.js
    │   └── runtime.js
    ├── signature1.xml
    └── tv7icon_117x117.png
```

**Comment by heaven-dev** [comment]
I am using gulp because I have one codebase, but from that codebase I generated four apps. It is quite complicated task. If you need only copy files from folder A to folder B you can do it with node. For example:
```js
/* add code below to file named copy-files.js */
/* code below is only partially tested (copy files) */

const fs = require('fs');
const path = require('path');
const process = require('process');

const targetFolders = ['tizen', 'build', 'js'];
const files = ['main.js', 'polyfills.js', 'runtime.js'];

/* create destination folders */
let path './';
targetFolders.forEach(folder => {
   if (!fs.existsSync(folder)){
       fs.mkdirSync(folder);
       process.chdir(folder);
   }
   path = path + folder + '/';
});

/* copy files */
files.forEach(file => {
  let from = path.resolve(__dirname, '..', './dist/', file);
  let to = path.resolve(__dirname, '..', 'tizen/build/js/', file);

  fs.readFile(from, 'utf-8', (err, data) => {
    if (err) {
      return;
    }

    fs.writeFile(to, data, (err) => {
      if (err) {
        return;
      }
    });
    console.log('File "' + file + '" copied to "dist/build/js" folder.')
  });
});
```

```js
/* package.json */
"scripts": {
    "copy-js": "node copy-files.js",
}
```

```js
/* run script */
npm run copy-js
```

**Comment by heaven-dev** [comment]
I am using gulp because I have one codebase, but from that codebase I generated 4 apps. It is quite complicated case. If you need only copy files from folder A to folder B you can do it with node. For example:

You need to install package: **npm install --save-dev fs-extra**

```js
/* add code below to file named copy-files.js */
/* code below is only partially tested (copy files) */

const fs = require('fs');
const path = require('path');
const process = require('process');
const fsextra = require('fs-extra');

const targetFolders = ['tizen', 'build', 'js'];
const files = ['main.js', 'polyfills.js', 'runtime.js'];

/** remove old build */
fsextra.remove('./tizen/build');

/* create destination folders */
let path '__dirname/';
targetFolders.forEach(folder => {
   path = path + folder;

   if (!fs.existsSync(path)){
       fs.mkdirSync(path);
   }

   path = path + '/';
   process.chdir(path);
});

/* copy files */
files.forEach(fileName => {
  let sourcePath = path.resolve(__dirname, '..', './dist/', fileName);
  let targetPath = path.resolve(__dirname, '..', 'tizen/build/js/', fileName);

  fs.readFile(sourcePath, 'utf-8', (error, fileData) => {
    if (error) {
      return;
    }

    fs.writeFile(targetPath, fileData, (error) => {
      if (error) {
        return;
      }
    });
  });
});
```

```js
/* package.json */
"scripts": {
    "copy-js": "node copy-files.js",
}
```

```js
/* run script */
npm run copy-js
```

**Comment by ionescu77** [comment]
Hey thank you for the last comment. Indeed.
Did not manage to implement yet.

I managed to use some tizen.system APIs and webapis.

I can only test my angular 10 app on a display (tizen 2.4 :( ) - with or without api's it only runs on tv and in chrome as angular app.

Your app runs on simulator and chrome. I will try to find a tizen > 3.0 to check.

I'll get back with feedback.

Thank you again for inspiration and guidance.
